CREATE DATABASE PROJECT_FINALEXAM
GO
USE PROJECT_FINALEXAM
GO

CREATE TABLE USERS
(
	USERS_ID INT IDENTITY(1,1),
	USERS_NAME NVARCHAR(255),
	USERNAME VARCHAR(25),
	PASS VARCHAR(25),
	DOB DATE,
	SEX VARCHAR(5),
	MSSV VARCHAR(25),
	SCHOOL NVARCHAR(255),
	PHONE VARCHAR(25),
	EMAIL VARCHAR(255),
	CURRENT_ADDRESS NVARCHAR(255),
	PRIMARY KEY (USERS_ID)
)
GO 
CREATE TABLE CATEGORY
(
	CATEGORY_ID VARCHAR(25),
	CATEGORY_NAME NVARCHAR(255),
	PRIMARY KEY (CATEGORY_ID)
)
GO
CREATE TABLE PRODUCT
(
	PRODUCT_ID INT IDENTITY(1,1),
	PRODUCT_NAME NVARCHAR(255),
	PRODUCT_DESCRIPTION TEXT,
	PRICE INT,
	SELL_DATE DATE,
	CATEGORY_ID VARCHAR(25),
	PRIMARY KEY (PRODUCT_ID)
)
GO
CREATE TABLE SELL
(
	USERS_ID INT ,
	PRODUCT_ID INT,
	TRADING_DATE DATE,
	STATUS BIT,
	PRIMARY KEY (USERS_ID, PRODUCT_ID)
)

GO
ALTER TABLE dbo.PRODUCT ADD FOREIGN KEY (CATEGORY_ID) REFERENCES dbo.CATEGORY(CATEGORY_ID)
ALTER TABLE dbo.SELL ADD FOREIGN KEY (USERS_ID) REFERENCES dbo.USERS (USERS_ID)
ALTER TABLE dbo.SELL ADD FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.PRODUCT (PRODUCT_ID)
	





